name: npm audit

on:
  pull_request:
  push:
    branches:
      - main
      - 'feature/*'
jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm install
        run: npm ci
      - uses: oke-py/npm-audit-action@v2
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oldbonez
          issue_labels: vulnerability,test
          dedupe_issues: true
