name: sastscan

env:
  DOCKER_PRD: oldbonedocker/ebsprd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '17 9 * * 5'

permissions:
  contents: read

jobs:
  dockerbuild:
    name: dockerbuild
    runs-on: "ubuntu-latest"
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t $DOCKER_PRD:$(date '+%Y-%m-%d')-${GITHUB_SHA:0:8} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: '$DOCKER_PRD:$(date '+%Y-%m-%d')-${GITHUB_SHA:0:8}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'


  snyk:
    name: snyk docker scan
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk to check Docker images for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: $DOCKER_PRD:$(date '+%Y-%m-%d')-${GITHUB_SHA:0:8}
          args: --file=Dockerfile --severity-threshold=high
      - name: Upload result to GitHub Code Scanning
            uses: github/codeql-action/upload-sarif@v2
            with:
              sarif_file: snyk.sarif
